name: Test and Lint
on: [push, pull_request, workflow_dispatch]
jobs:
  run_lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          golang-version: '1.15'
      - name: Downloading and installing deps
        run: |
          go mod vendor
          go mod download
      - name: Run linter
        run: make lint
      - name: Run test
        run: make test